luci: auto update rules and subscribe optimization
xiaorouji/openwrt-package pull request #3214
Opened 2024-05-22 09:49 UTC by lwb1978

1.新增循环更新模式，可设置间隔1-24小时循环更新，因cron天生缺陷，按时间间隔运行不准确，所以添加了新的脚本用于循环更新。
2.优化原更新设置选项中的一些用词和翻译，读起来可能更舒服些。
3.修改从计划任务或者循环脚本执行订阅更新、规则更新时不对crontab或者循环脚本进行操作，减少对其他程序计划任务的影响和避免循环脚本重新计时。

本次修改已在我自己的路由上运行验证并正常工作，涉及到6个文件修改和新增1个文件，麻烦大佬审核。
@xiaorouji

2024-05-23 17:32 UTC, Beginner-Go requested changes

2024-05-23 17:32 UTC, Beginner-Go commented on luci-app-passwall/root/usr/share/passwall/tasks.sh
> +done 2>/dev/null
```suggestion
done 2>/dev/null

```
1. 文件末端加换行
2. 把此文件 `chmod +x`

2024-05-23 18:01 UTC, lwb1978 commented on luci-app-passwall/root/usr/share/passwall/tasks.sh
> +done 2>/dev/null
谢谢大佬指点，第一点已经修改，第二点我查了下，在luci-app-passwall/root/etc/uci-defaults/luci-passwall脚本中有相关chmod 的代码：
chmod +x /usr/share/passwall/*.sh
应该不需要单独加了吧。

2024-05-24 15:11 UTC, Beginner-Go approved these changes

2024-05-25 09:02 UTC, merged