passwall: dns2socks: socks server selectable
xiaorouji/openwrt-package pull request #540
Opened 2020-07-22 09:39 UTC by peter-tank

Signed-off-by: peter-tank <30540412+peter-tank@users.noreply.github.com>

2020-07-22 10:47 UTC, Lienol commented
If the test is ok and you think it's time to merge, leave a message.

2020-07-22 15:16 UTC, peter-tank commented
@Lienol please review

2020-07-22 19:28 UTC, peter-tank commented
hold, the new UI has a problem on 19.07

2020-07-23 06:03 UTC, Lienol requested changes

2020-07-23 06:03 UTC, Lienol commented on lienol/luci-app-passwall/luasrc/model/cbi/passwall/global.lua
> +
get the socks status ajax request is not add.

2020-07-23 06:03 UTC, Lienol commented on lienol/luci-app-passwall/luasrc/model/cbi/passwall/other.lua
>  m:append(Template(appname .. "/other/footer"))
move it to the global.lua

2020-07-23 09:12 UTC, peter-tank commented
re-pushd, prevoisly tests fails on my wrong environments.

2020-07-23 12:09 UTC, merged